/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Museum.gltf --transform 
Files: .\Museum.gltf [196.56MB] > C:\Users\El\Documents\Projects\pepetoons-animations\app\museum\Museum-transformed.glb [3.36MB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Museum-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Painting-dapitan-church-curtains'].geometry} material={materials['Painting-dapitan-church-curtains']} position={[-4.558, 1.754, 0.449]} rotation={[Math.PI / 2, 0, -1.734]} scale={[1.27, 1.2, 1.11]} />
      <mesh geometry={nodes['Paintings-allegory-on-a-pair'].geometry} material={materials['Paintings-allegory-on-a-pair']} position={[0.448, 1.802, 4.601]} rotation={[1.596, -0.007, -0.075]} scale={[0.97, 1.01, 1.24]} />
      <mesh geometry={nodes['mother-of-pearl'].geometry} material={materials['mother-of-pearl']} position={[-0.442, 1.736, -4.549]} rotation={[Math.PI / 2, 0, -0.044]} scale={[1.32, 1, 1.09]} />
      <mesh geometry={nodes['Paintng-saturnina-rizal'].geometry} material={materials['Paintng-saturnina-rizal']} position={[4.575, 1.745, -0.46]} rotation={[1.571, 0.009, -1.681]} scale={[2.32, 1, 1.14]} />
      <mesh geometry={nodes['Sulpture-bust-of-mirabeau'].geometry} material={materials['Sulpture-bust-of-mirabeau']} position={[0.458, 1.755, 5.148]} rotation={[1.557, 0, -0.088]} scale={[2.04, 1, 0.98]} />
      <mesh geometry={nodes.Sketch_of_Himself.geometry} material={materials['Sketch of Himself']} position={[5.138, 1.752, -0.451]} rotation={[1.578, -0.018, -1.686]} scale={[2.66, 1, 1.04]} />
      <mesh geometry={nodes.Sketch_11.geometry} material={materials['Sketch 1.1']} position={[-0.447, 1.767, -5.139]} rotation={[Math.PI / 2, 0, 3.038]} scale={[1.44, 1, 1.03]} />
      <mesh geometry={nodes.Sculpture_11.geometry} material={materials['Sculpture 1.1']} position={[-5.147, 1.747, 0.464]} rotation={[1.575, -0.003, -1.699]} scale={[2.29, 1, 1.02]} />
      <mesh geometry={nodes.Bench_BenchConcreteBase_0.geometry} material={materials.BenchConcreteBase} rotation={[Math.PI, 0, 0]} scale={1.104} />
      <mesh geometry={nodes.Bench_BenchWood_0.geometry} material={materials.BenchWood} rotation={[Math.PI, 0, 0]} scale={1.104} />
      <mesh geometry={nodes.CeillingWire_CeillingWire_0.geometry} material={materials.CeillingWire} rotation={[-Math.PI / 2, 0, 0]} scale={[0.5, 0.5, 0.225]} />
      <mesh geometry={nodes.Lamp_Emissive_0.geometry} material={materials.Emissive} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Lamp_Lamp_0.geometry} material={materials.Lamp} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PaitingsInside_Painting_0.geometry} material={materials.Painting} rotation={[-Math.PI / 2, 0, 0.099]} />
      <mesh geometry={nodes.Walls_Ceilling_0.geometry} material={materials.Ceilling} rotation={[-Math.PI / 2, 0, 0]} scale={[0.5, 0.5, 0.225]} />
      <mesh geometry={nodes.Walls_Floor_0.geometry} material={materials.Floor} rotation={[-Math.PI / 2, 0, 0]} scale={[0.5, 0.5, 0.225]} />
      <mesh geometry={nodes.Walls_Walls_0.geometry} material={materials.Walls} rotation={[-Math.PI / 2, 0, 0]} scale={[0.5, 0.5, 0.225]} />
    </group>
  )
}

useGLTF.preload('/Museum-transformed.glb')
